package presentation;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;

public class SearchView extends JPanel {
    private JComboBox category;
    private JTextField inputField;
    private JLabel instrLabel;
    private JButton button;

    public SearchView() {
        //construct preComponents
        String[] categoryItems = {"Name", "Rating", "Calories", "Proteins", "Fat", "Sodium", "Price"};

        //construct components
        category = new JComboBox (categoryItems);
        inputField = new JTextField (5);
        instrLabel = new JLabel ("Choose the filtering option");
        button = new JButton ("Search");

        //adjust size and set layout
        setPreferredSize (new Dimension (165, 154));
        setLayout (null);

        //add components
        add (category);
        add (inputField);
        add (instrLabel);
        add (button);

        //set component bounds (only needed by Absolute Positioning)
        category.setBounds (5, 40, 145, 25);
        inputField.setBounds (5, 80, 145, 25);
        instrLabel.setBounds (0, 5, 165, 25);
        button.setBounds (15, 115, 120, 30);
    }


    public void display(){
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (this);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible (true);
    }

    public ArrayList<String> getInputs(){
        ArrayList<String> inputs = new ArrayList<>();
        inputs.add((String)category.getSelectedItem());
        inputs.add(inputField.getText());
        System.out.println(inputField.getText());
        return inputs;
    }

    public void addActions(ActionListener a){
        button.addActionListener(a);
    }
}

